//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StocksOwned
    {
        public int Id { get; set; }
        public string Symbol { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
        public int Owner { get; set; }
    }
}
