/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(j){j.initCustomLightbox=function(b,a,g){function k(){if(!a._lightbox){var c=a._getLightbox(),e=c.childNodes[1];c.className.indexOf("dhx_cal_light_wide")>=0?e.lastChild.firstChild.style.display="none":e.firstChild.style.display="none";e.style.height=e.style.height.replace("px","")-25+"px";c.style.height=c.style.height.replace("px","")-50+"px";c.style.width=+b.width+10+"px";e.style.width=b.width+"px"}return a._lightbox}var l=g+"_here_iframe_";a.config.buttons_left=[];a.config.buttons_right=
[];a._getLightbox=a.getLightbox;a.config.lightbox.sections=[{type:"frame",name:"box"}];a._cust_string_to_date=function(c){return a.templates.xml_date(c)};a._cust_date_to_str=function(c){return a.templates.xml_format(c)};a._deep_copy=function(a){if(typeof a=="object"){var e=Object.prototype.toString.call(a)=="[object Date]"?new Date(a):Object.prototype.toString.call(a)=="[object Array]"?[]:{},b;for(b in a)e[b]=j._deep_copy(a[b])}else e=a;return e};b.type=="external"?(a.attachEvent("onBeforeLightbox",
function(){a._custom_box_stage=0;return!0}),a.getLightbox=k,a._setLightboxValues=function(c,e){c=document.getElementById(l);try{switch(a._custom_box_stage){case 0:if(!a.dataProcessor){var d=a.dataProcessor=new DataProcessor;d.init(a)}var d=a.dataProcessor||d,f=d._getRowData(e),m=(b.view||"").indexOf("?")===-1?"?":"&",h="<form action='/"+b.view+m+"id="+encodeURIComponent(e)+"' method='POST'>",g;for(g in f)h+="<input type='hidden' name='"+g+"'/>";h+="</form>";var i=c.Document?c.Document.body:c.contentDocument.body;
i.innerHTML=h;var j=0;for(g in f)i.firstChild.childNodes[j++].value=f[g];i.firstChild.submit();break;case 1:if(!c.contentWindow.lightbox){var k=c.contentWindow;c.contentWindow.lightbox={close:function(){a._remove_customBox()}}}a.callEvent("onLightbox",[e]);break;case 2:if(!c)return;i=c.Document?c.Document.body:c.contentDocument.body;a._doLAction(i.textContent||i.innerText);a._remove_customBox()}}catch(n){a._remove_customBox()}a._custom_box_stage++},a._remove_customBox=function(){a._lightbox?a.endLightbox(!1,
a._lightbox):a.endLightbox(!1)},a._doLAction=function(c){try{var b=eval("("+c+")");if(b){var d=b.data;if(d.start_date&&d.end_date)d.start_date=a._cust_string_to_date(b.data.start_date),d.end_date=a._cust_string_to_date(b.data.end_date);var f=b.action;switch(b.action){case "insert":a._loading=!0;a.addEvent(d);a._loading=!1;f="inserted";break;case "update":var g=a.getEvent(b.sid),h;for(h in d)g[h]=d[h];a.event_updated(g);f="updated";break;case "delete":a.deleteEvent(b.sid,!0),f="deleted"}a.dataProcessor.callEvent("onAfterUpdate",
[b.sid,f,b.id,b])}}catch(j){}},a.form_blocks.frame={render:function(){return"<div style='display:inline-block; height:"+b.height+"px'></div>"},set_value:function(c,e,d){a._last_id=d.id;var f='<iframe id="'+l+"\" frameborder='0' onload='"+g+"._setLightboxValues(this, "+g+"._last_id)' src=''";if(b.width||b.height)f+=" style='";if(b.width)f+="width:"+b.width+"px;",c.style.width=b.width+"px";if(b.height)f+="height:"+b.height+"px;",c.style.height=b.height+"px";if(b.width||b.height)f+=" '";f+="><html></html></iframe>";
c.innerHTML=f;if(b.classname)c.className=b.classname;return!0},get_value:function(){return!0},focus:function(){return!0}},a._addEventFromFrame=function(){var a={}}):(a.form_blocks.frame={render:function(){var a='<iframe  id="'+g+"_here_iframe_\" onload='"+g+"._addLightboxInterface(this)' frameborder='0' src='"+b.view+"'";if(b.width||b.height)a+=" style='";b.width&&(a+="width:"+b.width+"px;");b.height&&(a+="height:"+b.height+"px;");if(b.width||b.height)a+=" '";a+=" ></iframe>";return a},set_value:function(a,
b,d){if(a.contentWindow&&a.contentWindow.setValues){if(a.contentWindow.document.getElementsByTagName("form").length==1)a.contentWindow.document.getElementsByTagName("form")[0].reset();else{var d=a.contentWindow.getValues(),f;for(f in d)d[f]="";a.contentWindow.setValues(d)}a.contentWindow.setValues(d)}},get_value:function(b){return a._deep_copy(b.contentWindow.getValues())},focus:function(){return!0}},a.getLightbox=k,a._addLightboxInterface=function(b){if(!b.contentWindow.lightbox)b.contentWindow.lightbox=
{};b.contentWindow.lightbox.save=function(){var d=a.getEvent(a.getState().lightbox_id),e=b.contentWindow.getValues(),g;for(g in e)d[g]=e[g];a.endLightbox(!0,a._lightbox)};b.contentWindow.lightbox.close=function(){a.endLightbox(!1,a._lightbox)};b.contentWindow.lightbox.remove=function(){var b=a.locale.labels.confirm_deleting;if(!b||confirm(b))a.deleteEvent(a._lightbox_id),a._new_event=null;a.endLightbox(!0,a._lightbox)};if(b.contentWindow.document.getElementsByTagName("form").length==1)b.contentWindow.document.getElementsByTagName("form")[0].reset();
else{var e=b.contentWindow.getValues(),d;for(d in e)e[d]="";b.contentWindow.setValues(e)}b.contentWindow.setValues(a.getEvent(a._lightbox_id));a.callEvent("onLightbox",[a._lightbox_id])})}});
