/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(a){(function(){var c=a.dhtmlXTooltip=a.tooltip={};c.config={className:"dhtmlXTooltip tooltip",timeout_to_display:50,timeout_to_hide:50,delta_x:15,delta_y:-20};c.tooltip=document.createElement("div");c.tooltip.className=c.config.className;c.show=function(d,j){if(!a.config.touch||a.config.touch_tooltip){var e=c,k=this.tooltip,b=k.style;e.tooltip.className=e.config.className;var i=this.position(d),l=d.target||d.srcElement;if(!this.isTooltip(l)){var f=0,g=0,h=a._obj;if(h.offsetParent){do f+=
h.offsetLeft,g+=h.offsetTop;while(h=h.offsetParent)}var m=i.x+(e.config.delta_x||0)-f,n=i.y-(e.config.delta_y||0)-g;b.visibility="hidden";b.removeAttribute?(b.removeAttribute("right"),b.removeAttribute("bottom")):(b.removeProperty("right"),b.removeProperty("bottom"));b.left="0";b.top="0";this.tooltip.innerHTML=j;document.body.appendChild(this.tooltip);var o=this.tooltip.offsetWidth,p=this.tooltip.offsetHeight;a._obj.offsetWidth-m-(a.xy.margin_left||0)-o<0?(b.removeAttribute?b.removeAttribute("left"):
b.removeProperty("left"),b.right=a._obj.offsetWidth-m+2*(e.config.delta_x||0)+"px"):b.left=m<0?i.x+Math.abs(e.config.delta_x||0)+"px":m+"px";a._obj.offsetHeight-n-(a.xy.margin_top||0)-p<0?(b.removeAttribute?b.removeAttribute("top"):b.removeProperty("top"),b.bottom=a._obj.offsetHeight-n-2*(e.config.delta_y||0)+"px"):b.top=n<0?i.y+Math.abs(e.config.delta_y||0)+"px":n+"px";b.visibility="visible";a.callEvent("onTooltipDisplayed",[this.tooltip,this.tooltip.event_id])}}};c._clearTimeout=function(){this.tooltip._timeout_id&&
window.clearTimeout(this.tooltip._timeout_id)};c.hide=function(){if(this.tooltip.parentNode){var d=this.tooltip.event_id;this.tooltip.event_id=null;this.tooltip.parentNode.removeChild(this.tooltip);a.callEvent("onAfterTooltip",[d])}this._clearTimeout()};c.delay=function(d,a,e,c){this.tooltip._timeout_id&&window.clearTimeout(this.tooltip._timeout_id);this.tooltip._timeout_id=setTimeout(function(){var b=d.apply(a,e);d=a=e=null;return b},c||this.config.timeout_to_display)};c.isTooltip=function(d){var a=
!1;for(d.className.split(" ");d&&!a;)a=d.className==this.tooltip.className,d=d.parentNode;return a};c.position=function(a){a=a||window.event;if(a.pageX||a.pageY)return{x:a.pageX,y:a.pageY};var c=window._isIE&&document.compatMode!="BackCompat"?document.documentElement:document.body;return{x:a.clientX+c.scrollLeft-c.clientLeft,y:a.clientY+c.scrollTop-c.clientTop}};a.attachEvent("onMouseMove",function(d,j){var e=window.event||j,k=e.target||e.srcElement,b=c,i=b.isTooltip(k),l=b.isTooltipTarget&&b.isTooltipTarget(k);
if(d||i||l){var f;if(d||b.tooltip.event_id){var g=a.getEvent(d)||a.getEvent(b.tooltip.event_id);if(!g)return;b.tooltip.event_id=g.id;f=a.templates.tooltip_text(g.start_date,g.end_date,g);if(!f)return b.hide()}l&&(f="");var h=void 0;_isIE&&(h=document.createEventObject(e));a.callEvent("onBeforeTooltip",[d])&&f&&b.delay(b.show,b,[h||e,f])}else b.delay(b.hide,b,[],b.config.timeout_to_hide)});a.attachEvent("onBeforeDrag",function(){c.hide();return!0});a.attachEvent("onEventDeleted",function(){c.hide();
return!0});a.templates.tooltip_date_format=a.date.date_to_str("%Y-%m-%d %H:%i");a.templates.tooltip_text=function(c,j,e){return"<b>Event:</b> "+e.text+"<br/><b>Start date:</b> "+a.templates.tooltip_date_format(c)+"<br/><b>End date:</b> "+a.templates.tooltip_date_format(j)}})()});
