/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(b){b.config.icons_select=["icon_details","icon_delete"];b.config.details_on_create=!0;b.xy.menu_width=0;b.attachEvent("onClick",function(c){b.showQuickInfo(c);return!0});(function(){for(var c=["onEmptyClick","onViewChange","onLightbox","onBeforeEventDelete","onBeforeDrag"],a=function(){b._hideQuickInfo();return!0},d=0;d<c.length;d++)b.attachEvent(c[d],a)})();b.templates.quick_info_title=function(b,a,d){return d.text.substr(0,50)};b.templates.quick_info_content=function(b,
a,d){return d.details||d.text};b.templates.quick_info_date=function(c,a,d){return b.is_one_day_event(d)?b.templates.day_date(c,a,d)+" "+b.templates.event_header(c,a,d):b.templates.week_date(c,a,d)};b.showQuickInfo=function(b){if(b!=this._quick_info_box_id){this.hideQuickInfo(!0);var a=this._get_event_counter_part(b);if(a)this._quick_info_box=this._init_quick_info(a),this._fill_quick_data(b),this._show_quick_info(a)}};b._hideQuickInfo=function(){b.hideQuickInfo()};b.hideQuickInfo=function(c){var a=
this._quick_info_box;this._quick_info_box_id=0;if(a&&a.parentNode){if(b.config.quick_info_detached)return a.parentNode.removeChild(a);a.style.right=="auto"?a.style.left="-350px":a.style.right="-350px";c&&a.parentNode.removeChild(a)}};dhtmlxEvent(window,"keydown",function(c){c.keyCode==27&&b.hideQuickInfo()});b._show_quick_info=function(c){var a=b._quick_info_box;if(b.config.quick_info_detached){b._obj.appendChild(a);var d=a.offsetWidth,f=a.offsetHeight;a.style.left=c.left-c.dx*(d-c.width)+"px";a.style.top=
c.top-(c.dy?f:-c.height)+"px"}else a.style.top=this.xy.scale_height+this.xy.nav_height+20+"px",c.dx==1?(a.style.right="auto",a.style.left="-300px",setTimeout(function(){a.style.left="-10px"},1)):(a.style.left="auto",a.style.right="-300px",setTimeout(function(){a.style.right="-10px"},1)),a.className=a.className.replace("dhx_qi_left","").replace("dhx_qi_left","")+" dhx_qi_"+(c==1?"left":"right"),b._obj.appendChild(a)};b._init_quick_info=function(){if(!this._quick_info_box){var c=b.xy,a=this._quick_info_box=
document.createElement("div");a.className="dhx_cal_quick_info";var d='<div class="dhx_cal_qi_title" style="height:'+c.quick_info_title+'px"><div class="dhx_cal_qi_tcontent"></div><div  class="dhx_cal_qi_tdate"></div></div><div class="dhx_cal_qi_content"></div>';d+='<div class="dhx_cal_qi_controls" style="height:'+c.quick_info_buttons+'px">';for(var f=b.config.icons_select,e=0;e<f.length;e++)d+='<div class="dhx_qi_big_icon '+f[e]+'" title="'+b.locale.labels[f[e]]+"\"><div class='dhx_menu_icon "+f[e]+
"'></div><div>"+b.locale.labels[f[e]]+"</div></div>";d+="</div>";a.innerHTML=d;dhtmlxEvent(a,"click",function(a){a=a||event;b._qi_button_click(a.target||a.srcElement)});b.config.quick_info_detached&&dhtmlxEvent(b._els.dhx_cal_data[0],"scroll",function(){b.hideQuickInfo()})}return this._quick_info_box};b._qi_button_click=function(c){var a=b._quick_info_box;if(c&&c!=a){var d=c.className;if(d.indexOf("_icon")!=-1){var f=b._quick_info_box_id;b._click.buttons[d.split(" ")[1].replace("icon_","")](f)}else b._qi_button_click(c.parentNode)}};
b._get_event_counter_part=function(c){for(var a=b.getRenderedEvent(c),d=0,f=0,e=a;e&&e!=b._obj;)d+=e.offsetLeft,f+=e.offsetTop-e.scrollTop,e=e.offsetParent;if(e){var g=d+a.offsetWidth/2>b._x/2?1:0,h=f+a.offsetHeight/2>b._y/2?1:0;return{left:d,top:f,dx:g,dy:h,width:a.offsetWidth,height:a.offsetHeight}}return 0};b._fill_quick_data=function(c){var a=b.getEvent(c),d=b._quick_info_box;b._quick_info_box_id=c;var f=d.firstChild.firstChild;f.innerHTML=b.templates.quick_info_title(a.start_date,a.end_date,
a);var e=f.nextSibling;e.innerHTML=b.templates.quick_info_date(a.start_date,a.end_date,a);var g=d.firstChild.nextSibling;g.innerHTML=b.templates.quick_info_content(a.start_date,a.end_date,a)}});
