/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(a){if(typeof dataProcessor!=="undefined"){var h=dataProcessor.prototype.init;dataProcessor.prototype.init=function(){h.apply(this,arguments);var d=this;this.attachEvent("onAfterUpdate",function(b,a,c){var e;e=d.obj.exists(b)?d.obj.item(b):{};typeof e.$selected!=="undefined"&&delete e.$selected;typeof e.$template!=="undefined"&&delete e.$template;d.callEvent("onLocalUpdate",[{sid:b,tid:c,status:a,data:e}])})};dataProcessor.prototype.applyChanges=function(d){var b=this,a=d.sid,
c=d.tid,e=d.status,f=d.data;if(b.obj.isSelected(a))f.$selected=!0;switch(e){case "updated":case "update":case "inserted":case "insert":b.obj.exists(a)?(b.obj.isLUEdit(f)===a&&b.obj.stopEditBefore(),b.ignore(function(){b.obj.update(a,f);a!==c&&b.obj.changeId(a,c)})):(f.id=c,b.ignore(function(){b.obj.add(f)}));break;case "deleted":case "delete":b.ignore(function(){b.obj.exists(a)&&(b.obj.setUserData(a,"!nativeeditor_status","true_deleted"),b.obj.stopEditBefore(),b.obj.remove(a),b.obj.isLUEdit(f)===
a&&(b.obj.preventLUCollision(f),b.obj.callEvent("onLiveUpdateCollision",[a,c,e,f])===!1&&b.obj.stopEditAfter()))})}}}if(typeof a!=="undefined")a.item=function(d){var b=this.getEvent(d);if(!b)return{};var g={},c;for(c in b)g[c]=b[c];g.start_date=a.date.date_to_str(a.config.api_date)(b.start_date);g.end_date=a.date.date_to_str(a.config.api_date)(b.end_date);return g},a.update=function(d,b){var g=this.getEvent(d),c;for(c in b)c!="start_date"&&c!="end_date"&&(g[c]=b[c]);var e=a.date.str_to_date(a.config.api_date);
a.setEventStartDate(d,e(b.start_date));a.setEventEndDate(d,e(b.end_date));this.updateEvent(d)},a.remove=function(a){this.exists(a)&&this.deleteEvent(a,!0)},a.exists=function(a){var b=this.getEvent(a);return b?!0:!1},a.add=function(a){return this.addEvent(a.start_date,a.end_date,a.text,a.id,a)},a.changeId=function(a,b){return this.changeEventId(a,b)},a.stopEditBefore=function(){},a.stopEditAfter=function(){this.endLightbox(!1,this._lightbox)},a.preventLUCollision=function(a){this._new_event=this._lightbox_id;
a.id=this._lightbox_id;this._events[this._lightbox_id]=a},a.isLUEdit=function(){return this._lightbox_id?this._lightbox_id:null},a.isSelected=function(){return!1}});
