/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(a){a.templates.calendar_month=a.date.date_to_str("%F %Y");a.templates.calendar_scale_date=a.date.date_to_str("%D");a.templates.calendar_date=a.date.date_to_str("%d");a.config.minicalendar={mark_events:!0};a._synced_minicalendars=[];a.renderCalendar=function(d,b,c){var e=null,g=d.date||a._currentDate();typeof g=="string"&&(g=this.templates.api_date(g));if(b)e=this._render_calendar(b.parentNode,g,d,b),a.unmarkCalendar(e);else{var f=d.container,i=d.position;typeof f=="string"&&
(f=document.getElementById(f));typeof i=="string"&&(i=document.getElementById(i));if(i&&typeof i.left=="undefined")var l=getOffset(i),i={top:l.top+i.offsetHeight,left:l.left};f||(f=a._get_def_cont(i));e=this._render_calendar(f,g,d);e.onclick=function(d){var d=d||event,b=d.target||d.srcElement;if(b.className.indexOf("dhx_month_head")!=-1){var c=b.parentNode.className;if(c.indexOf("dhx_after")==-1&&c.indexOf("dhx_before")==-1){var e=a.templates.xml_date(this.getAttribute("date"));e.setDate(parseInt(b.innerHTML,
10));a.unmarkCalendar(this);a.markCalendar(this,e,"dhx_calendar_click");this._last_date=e;this.conf.handler&&this.conf.handler.call(a,e,this)}}}}if(a.config.minicalendar.mark_events)for(var k=a.date.month_start(g),o=a.date.add(k,1,"month"),m=this.getEvents(k,o),t=this["filter_"+this._mode],q=0;q<m.length;q++){var h=m[q];if(!t||t(h.id,h)){var j=h.start_date;j.valueOf()<k.valueOf()&&(j=k);for(j=a.date.date_part(new Date(j.valueOf()));j<h.end_date;)if(this.markCalendar(e,j,"dhx_year_event"),j=this.date.add(j,
1,"day"),j.valueOf()>=o.valueOf())break}}this._markCalendarCurrentDate(e);e.conf=d;d.sync&&!c&&this._synced_minicalendars.push(e);return e};a._get_def_cont=function(a){if(!this._def_count)this._def_count=document.createElement("DIV"),this._def_count.className="dhx_minical_popup",this._def_count.onclick=function(a){(a||event).cancelBubble=!0},document.body.appendChild(this._def_count);this._def_count.style.left=a.left+"px";this._def_count.style.top=a.top+"px";this._def_count._created=new Date;return this._def_count};
a._locateCalendar=function(d,b){var c=d.childNodes[2].childNodes[0];typeof b=="string"&&(b=a.templates.api_date(b));var e=d.week_start+b.getDate()-1;return c.rows[Math.floor(e/7)].cells[e%7].firstChild};a.markCalendar=function(a,b,c){this._locateCalendar(a,b).className+=" "+c};a.unmarkCalendar=function(a,b,c){b=b||a._last_date;c=c||"dhx_calendar_click";if(b){var e=this._locateCalendar(a,b);e.className=(e.className||"").replace(RegExp(c,"g"))}};a._week_template=function(d){for(var b=d||250,c=0,e=document.createElement("div"),
g=this.date.week_start(a._currentDate()),f=0;f<7;f++)this._cols[f]=Math.floor(b/(7-f)),this._render_x_header(f,c,g,e),g=this.date.add(g,1,"day"),b-=this._cols[f],c+=this._cols[f];e.lastChild.className+=" dhx_scale_bar_last";return e};a.updateCalendar=function(a,b){a.conf.date=b;this.renderCalendar(a.conf,a,!0)};a._mini_cal_arrows=["&nbsp","&nbsp"];a._render_calendar=function(d,b,c,e){var g=a.templates,f=this._cols;this._cols=[];var i=this._mode;this._mode="calendar";var l=this._colsS;this._colsS=
{height:0};var k=new Date(this._min_date),o=new Date(this._max_date),m=new Date(a._date),t=g.month_day;g.month_day=g.calendar_date;var b=this.date.month_start(b),q=this._week_template(d.offsetWidth-1),h;e?h=e:(h=document.createElement("DIV"),h.className="dhx_cal_container dhx_mini_calendar");h.setAttribute("date",this.templates.xml_format(b));h.innerHTML="<div class='dhx_year_month'></div><div class='dhx_year_week'>"+q.innerHTML+"</div><div class='dhx_year_body'></div>";h.childNodes[0].innerHTML=
this.templates.calendar_month(b);if(c.navigation)for(var j=function(b,d){var c=a.date.add(b._date,d,"month");a.updateCalendar(b,c);a._date.getMonth()==b._date.getMonth()&&a._date.getFullYear()==b._date.getFullYear()&&a._markCalendarCurrentDate(b)},x=["dhx_cal_prev_button","dhx_cal_next_button"],y=["left:1px;top:2px;position:absolute;","left:auto; right:1px;top:2px;position:absolute;"],z=[-1,1],A=function(b){return function(){if(c.sync)for(var d=a._synced_minicalendars,e=0;e<d.length;e++)j(d[e],b);
else j(h,b)}},p=0;p<2;p++){var r=document.createElement("DIV");r.className=x[p];r.style.cssText=y[p];r.innerHTML=this._mini_cal_arrows[p];h.firstChild.appendChild(r);r.onclick=A(z[p])}h._date=new Date(b);h.week_start=(b.getDay()-(this.config.start_on_monday?1:0)+7)%7;var B=this.date.week_start(b);this._reset_month_scale(h.childNodes[2],b,B);for(var n=h.childNodes[2].firstChild.rows,s=n.length;s<6;s++){var w=n[n.length-1];n[0].parentNode.appendChild(w.cloneNode(!0));for(var u=parseInt(w.childNodes[w.childNodes.length-
1].childNodes[0].innerHTML),u=u<10?u:0,v=0;v<n[s].childNodes.length;v++)n[s].childNodes[v].className="dhx_after",n[s].childNodes[v].childNodes[0].innerHTML=a.date.to_fixed(++u)}e||d.appendChild(h);h.childNodes[1].style.height=h.childNodes[1].childNodes[0].offsetHeight-1+"px";this._cols=f;this._mode=i;this._colsS=l;this._min_date=k;this._max_date=o;a._date=m;g.month_day=t;return h};a.destroyCalendar=function(a,b){if(!a&&this._def_count&&this._def_count.firstChild&&(b||(new Date).valueOf()-this._def_count._created.valueOf()>
500))a=this._def_count.firstChild;if(a&&(a.onclick=null,a.innerHTML="",a.parentNode&&a.parentNode.removeChild(a),this._def_count))this._def_count.style.top="-1000px"};a.isCalendarVisible=function(){return this._def_count&&parseInt(this._def_count.style.top,10)>0?this._def_count:!1};a.attachEvent("onTemplatesReady",function(){dhtmlxEvent(document.body,"click",function(){a.destroyCalendar()})});a.templates.calendar_time=a.date.date_to_str("%d-%m-%Y");a.form_blocks.calendar_time={render:function(){var d=
"<input class='dhx_readonly' type='text' readonly='true'>",b=a.config,c=this.date.date_part(a._currentDate()),e=1440,g=0;b.limit_time_select&&(g=60*b.first_hour,e=60*b.last_hour+1);c.setHours(g/60);d+=" <select>";for(var f=g;f<e;f+=this.config.time_step*1){var i=this.templates.time_picker(c);d+="<option value='"+f+"'>"+i+"</option>";c=this.date.add(c,this.config.time_step,"minute")}d+="</select>";var l=a.config.full_day;return"<div style='height:30px;padding-top:0; font-size:inherit;' class='dhx_section_time'>"+
d+"<span style='font-weight:normal; font-size:10pt;'> &nbsp;&ndash;&nbsp; </span>"+d+"</div>"},set_value:function(d,b,c){function e(b,c,d){i(b,c,d);b.value=a.templates.calendar_time(c);b._date=a.date.date_part(new Date(c))}var g=d.getElementsByTagName("input"),f=d.getElementsByTagName("select"),i=function(b,c,d){b.onclick=function(){a.destroyCalendar(null,!0);a.renderCalendar({position:b,date:new Date(this._date),navigation:!0,handler:function(c){b.value=a.templates.calendar_time(c);b._date=new Date(c);
a.destroyCalendar();a.config.event_duration&&a.config.auto_end_date&&d==0&&m()}})}};if(a.config.full_day){if(!d._full_day){var l="<label class='dhx_fullday'><input type='checkbox' name='full_day' value='true'> "+a.locale.labels.full_day+"&nbsp;</label></input>";a.config.wide_form||(l=d.previousSibling.innerHTML+l);d.previousSibling.innerHTML=l;d._full_day=!0}var k=d.previousSibling.getElementsByTagName("input")[0],o=a.date.time_part(c.start_date)==0&&a.date.time_part(c.end_date)==0;k.checked=o;f[0].disabled=
k.checked;f[1].disabled=k.checked;k.onclick=function(){if(k.checked==!0){var b={};a.form_blocks.calendar_time.get_value(d,b);var i=a.date.date_part(b.start_date),h=a.date.date_part(b.end_date);if(+h==+i||+h>=+i&&(c.end_date.getHours()!=0||c.end_date.getMinutes()!=0))h=a.date.add(h,1,"day")}var j=i||c.start_date,l=h||c.end_date;e(g[0],j);e(g[1],l);f[0].value=j.getHours()*60+j.getMinutes();f[1].value=l.getHours()*60+l.getMinutes();f[0].disabled=k.checked;f[1].disabled=k.checked}}if(a.config.event_duration&&
a.config.auto_end_date){var m=function(){start_date=a.date.add(g[0]._date,f[0].value,"minute");end_date=new Date(start_date.getTime()+a.config.event_duration*6E4);g[1].value=a.templates.calendar_time(end_date);g[1]._date=a.date.date_part(new Date(end_date));f[1].value=end_date.getHours()*60+end_date.getMinutes()};f[0].onchange=m}e(g[0],c.start_date,0);e(g[1],c.end_date,1);i=function(){};f[0].value=c.start_date.getHours()*60+c.start_date.getMinutes();f[1].value=c.end_date.getHours()*60+c.end_date.getMinutes()},
get_value:function(d,b){var c=d.getElementsByTagName("input"),e=d.getElementsByTagName("select");b.start_date=a.date.add(c[0]._date,e[0].value,"minute");b.end_date=a.date.add(c[1]._date,e[1].value,"minute");if(b.end_date<=b.start_date)b.end_date=a.date.add(b.start_date,a.config.time_step,"minute")},focus:function(){}};a.linkCalendar=function(d,b){var c=function(){var c=a._date,g=new Date(c.valueOf());b&&(g=b(g));g.setDate(1);a.updateCalendar(d,g);return!0};a.attachEvent("onViewChange",c);a.attachEvent("onXLE",
c);a.attachEvent("onEventAdded",c);a.attachEvent("onEventChanged",c);a.attachEvent("onAfterEventDelete",c);c()};a._markCalendarCurrentDate=function(d){var b=a._date,c=a._mode,e=a.date.month_start(new Date(d._date)),g=a.date.add(e,1,"month");if(c=="day"||this._props&&this._props[c])e.valueOf()<=b.valueOf()&&g>b&&a.markCalendar(d,b,"dhx_calendar_click");else if(c=="week")for(var f=a.date.week_start(new Date(b.valueOf())),i=0;i<7;i++)e.valueOf()<=f.valueOf()&&g>f&&a.markCalendar(d,f,"dhx_calendar_click"),
f=a.date.add(f,1,"day")};a.attachEvent("onEventCancel",function(){a.destroyCalendar(null,!0)})});
