/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(b){(function(){function h(a){return a.replace(newline_regexp,"\n").replace(html_regexp,"")}function y(a,b){a=parseFloat(a);b=parseFloat(b);isNaN(b)||(a-=b);var d=t(a),a=a-d.width+d.cols*i;return isNaN(a)?"auto":100*a/i}function C(a,b,d){a=parseFloat(a);b=parseFloat(b);!isNaN(b)&&d&&(a-=b);var e=t(a),a=a-e.width+e.cols*i;return isNaN(a)?"auto":100*a/(i-(!isNaN(b)?b:0))}function t(a){for(var f=0,d=b._els.dhx_cal_header[0].childNodes,e=d[1]?d[1].childNodes:d[0].childNodes,c=
0;c<e.length;c++){var g=e[c].style?e[c]:e[c].parentNode,h=parseFloat(g.style.width);if(a>h)a-=h+1,f+=h+1;else break}return{width:f,cols:c}}function z(a){a=parseFloat(a);return isNaN(a)?"auto":100*a/o}function l(a,b){return(window.getComputedStyle?window.getComputedStyle(a,null)[b]:a.currentStyle?a.currentStyle[b]:null)||""}function G(a,f){for(var d=parseInt(a.style.left,10),e=0;e<b._cols.length;e++)if(d-=b._cols[e],d<0)return e;return f}function H(a,f){for(var d=parseInt(a.style.top,10),e=0;e<b._colsS.heights.length;e++)if(b._colsS.heights[e]>
d)return e;return f}function I(a){return a?"<"+a+">":""}function r(a){return a?"</"+a+">":""}function u(a,b,d,e){var c="<"+a+" profile='"+b+"'";d&&(c+=" header='"+d+"'");e&&(c+=" footer='"+e+"'");c+=">";return c}function v(){var a="",f=b._mode;b.matrix&&b.matrix[b._mode]&&(f=b.matrix[b._mode].render=="cell"?"matrix":"timeline");a+="<scale mode='"+f+"' today='"+b._els.dhx_cal_date[0].innerHTML+"'>";if(b._mode=="week_agenda")for(var d=b._els.dhx_cal_data[0].getElementsByTagName("DIV"),e=0;e<d.length;e++)d[e].className==
"dhx_wa_scale_bar"&&(a+="<column>"+h(d[e].innerHTML)+"</column>");else if(b._mode=="agenda"||b._mode=="map")d=b._els.dhx_cal_header[0].childNodes[0].childNodes,a+="<column>"+h(d[0].innerHTML)+"</column><column>"+h(d[1].innerHTML)+"</column>";else if(b._mode=="year"){d=b._els.dhx_cal_data[0].childNodes;for(e=0;e<d.length;e++)a+="<month label='"+h(d[e].childNodes[0].innerHTML)+"'>",a+=s(d[e].childNodes[1].childNodes),a+=w(d[e].childNodes[2]),a+="</month>"}else{a+="<x>";d=b._els.dhx_cal_header[0].childNodes;
a+=s(d);a+="</x>";var c=b._els.dhx_cal_data[0];if(b.matrix&&b.matrix[b._mode]){a+="<y>";for(e=0;e<c.firstChild.rows.length;e++){var g=c.firstChild.rows[e];a+="<row><![CDATA["+h(g.cells[0].innerHTML)+"]]\></row>"}a+="</y>";o=c.firstChild.rows[0].cells[0].offsetHeight}else if(c.firstChild.tagName=="TABLE")a+=w(c);else{for(c=c.childNodes[c.childNodes.length-1];c.className.indexOf("dhx_scale_holder")==-1;)c=c.previousSibling;c=c.childNodes;a+="<y>";for(e=0;e<c.length;e++)a+="\n<row><![CDATA["+h(c[e].innerHTML)+
"]]\></row>";a+="</y>";o=c[0].offsetHeight}}a+="</scale>";return a}function w(a){for(var b="",d=a.firstChild.rows,e=0;e<d.length;e++){for(var c=[],g=0;g<d[e].cells.length;g++)c.push(d[e].cells[g].firstChild.innerHTML);b+="\n<row height='"+a.firstChild.rows[e].cells[0].offsetHeight+"'><![CDATA["+h(c.join("|"))+"]]\></row>";o=a.firstChild.rows[0].cells[0].offsetHeight}return b}function s(a){var f="";if(b.matrix&&b.matrix[b._mode]){if(b.matrix[b._mode].second_scale)var d=a[1].childNodes;a=a[0].childNodes}for(var e=
0;e<a.length;e++)f+="\n<column><![CDATA["+h(a[e].innerHTML)+"]]\></column>";i=a[0].offsetWidth;if(d)for(var c=0,g=a[0].offsetWidth,p=1,e=0;e<d.length;e++)f+="\n<column second_scale='"+p+"'><![CDATA["+h(d[e].innerHTML)+"]]\></column>",c+=d[e].offsetWidth,c>=g&&(g+=a[p]?a[p].offsetWidth:0,p++),i=d[0].offsetWidth;return f}function D(a){var f="",d=b._rendered,e=b.matrix&&b.matrix[b._mode];if(b._mode=="agenda"||b._mode=="map")for(var c=0;c<d.length;c++)f+="<event><head>"+h(d[c].childNodes[0].innerHTML)+
"</head><body>"+h(d[c].childNodes[2].innerHTML)+"</body></event>";else if(b._mode=="week_agenda")for(c=0;c<d.length;c++)f+="<event day='"+d[c].parentNode.getAttribute("day")+"'><body>"+h(d[c].innerHTML)+"</body></event>";else if(b._mode=="year"){d=b.get_visible_events();for(c=0;c<d.length;c++){var g=d[c].start_date;if(g.valueOf()<b._min_date.valueOf())g=b._min_date;for(;g<d[c].end_date;){var p=g.getMonth()+12*(g.getFullYear()-b._min_date.getFullYear())-b.week_starts._month,q=b.week_starts[p]+g.getDate()-
1,k=a?l(b._get_year_cell(g),"color"):"",j=a?l(b._get_year_cell(g),"backgroundColor"):"";f+="<event day='"+q%7+"' week='"+Math.floor(q/7)+"' month='"+p+"' backgroundColor='"+j+"' color='"+k+"'></event>";g=b.date.add(g,1,"day");if(g.valueOf()>=b._max_date.valueOf())break}}}else if(e&&e.render=="cell"){d=b._els.dhx_cal_data[0].getElementsByTagName("TD");for(c=0;c<d.length;c++)k=a?l(d[c],"color"):"",j=a?l(d[c],"backgroundColor"):"",f+="\n<event><body backgroundColor='"+j+"' color='"+k+"'><![CDATA["+h(d[c].innerHTML)+
"]]\></body></event>"}else for(c=0;c<d.length;c++){var m,i;if(b.matrix&&b.matrix[b._mode])m=y(d[c].style.left),i=y(d[c].offsetWidth)-1;else{var E=b.config.use_select_menu_space?0:26;m=C(d[c].style.left,E,!0);i=C(d[c].style.width,E)-1}if(!isNaN(i*1)){var n=z(d[c].style.top),r=z(d[c].style.height),A=d[c].className.split(" ")[0].replace("dhx_cal_","");if(A!=="dhx_tooltip_line"){var B=b.getEvent(d[c].getAttribute("event_id")),q=B._sday,x=B._sweek,t=B._length||0;if(b._mode=="month")r=parseInt(d[c].offsetHeight,
10),n=parseInt(d[c].style.top,10)-22,q=G(d[c],q),x=H(d[c],x);else if(b.matrix&&b.matrix[b._mode]){var q=0,u=d[c].parentNode.parentNode.parentNode,x=u.rowIndex,v=o;o=d[c].parentNode.offsetHeight;n=z(d[c].style.top);n-=n*0.2;o=v}else{if(d[c].parentNode==b._els.dhx_cal_data[0])continue;var s=b._els.dhx_cal_data[0].childNodes[0],w=parseFloat(s.className.indexOf("dhx_scale_holder")!=-1?s.style.left:0);m+=y(d[c].parentNode.style.left,w)}f+="\n<event week='"+x+"' day='"+q+"' type='"+A+"' x='"+m+"' y='"+
n+"' width='"+i+"' height='"+r+"' len='"+t+"'>";A=="event"?(f+="<header><![CDATA["+h(d[c].childNodes[1].innerHTML)+"]]\></header>",k=a?l(d[c].childNodes[2],"color"):"",j=a?l(d[c].childNodes[2],"backgroundColor"):"",f+="<body backgroundColor='"+j+"' color='"+k+"'><![CDATA["+h(d[c].childNodes[2].innerHTML)+"]]\></body>"):(k=a?l(d[c],"color"):"",j=a?l(d[c],"backgroundColor"):"",f+="<body backgroundColor='"+j+"' color='"+k+"'><![CDATA["+h(d[c].innerHTML)+"]]\></body>");f+="</event>"}}}return f}function F(a,
f,d,e,c,g,h){var i=!1;c=="fullcolor"&&(i=!0,c="color");c=c||"color";html_regexp=RegExp("<[^>]*>","g");newline_regexp=RegExp("<br[^>]*>","g");var k=b.uid(),j=document.createElement("div");j.style.display="none";document.body.appendChild(j);j.innerHTML='<form id="'+k+'" method="post" target="_blank" action="'+e+'" accept-charset="utf-8" enctype="application/x-www-form-urlencoded"><input type="hidden" name="mycoolxmlbody"/> </form>';var m="";if(a){for(var l=b._date,o=b._mode,m=u("pages",c,g,h),n=new Date(a);+n<
+f;n=b.date.add(n,1,d))b.setCurrentView(n,d),m+=I("page")+v().replace("\u2013","-")+D(i)+r("page");m+=r("pages");b.setCurrentView(l,o)}else m=u("data",c,g,h)+v().replace("\u2013","-")+D(i)+r("data");document.getElementById(k).firstChild.value=encodeURIComponent(m);document.getElementById(k).submit();j.parentNode.removeChild(j)}var i,o;b.toPDF=function(a,b,d,e){return F.apply(this,[null,null,null,a,b,d,e])};b.toPDFRange=function(a,f,d,e,c,g,h){typeof a=="string"&&(a=b.templates.api_date(a),f=b.templates.api_date(f));
return F.apply(this,arguments)}})()});
