/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(a){(function(){function H(){for(var b=a.get_visible_events(),d=[],c=0;c<this.y_unit.length;c++)d[c]=[];d[e]||(d[e]=[]);for(c=0;c<b.length;c++){for(var e=this.order[b[c][this.y_property]],i=0;this._trace_x[i+1]&&b[c].start_date>=this._trace_x[i+1];)i++;for(;this._trace_x[i]&&b[c].end_date>this._trace_x[i];)d[e][i]||(d[e][i]=[]),d[e][i].push(b[c]),i++}return d}function D(a){for(var d=0,c=this._trace_x;d<c.length-1&&+a>=+c[d+1];)d++;return d}function w(b,d,c){var e=0,i=c._step,
f=c.round_position,j=0,g=d?b.end_date:b.start_date;if(g.valueOf()>a._max_date.valueOf())g=a._max_date;var l=g-a._min_date_timeline;if(l>0){for(var o=D.call(c,g),n=0;n<o;n++)e+=a._cols[n];var m=a.date.add(a._min_date_timeline,a.matrix[a._mode].x_step*o,a.matrix[a._mode].x_unit);f?+g>+m&&d&&(j=a._cols[o]):(l=g-m,j=Math.round(l/i))}e+=d?l!=0&&!f?j-12:j-14:j+1;return e}function y(b,d){var c=D.call(this,b),e=this._trace_x[c];d&&+b!=+this._trace_x[c]&&(e=this._trace_x[c+1]?this._trace_x[c+1]:a.date.add(this._trace_x[c],
this.x_step,this.x_unit));return new Date(e)}function I(b){var d="";if(b&&this.render!="cell"){b.sort(this.sort||function(a,b){return a.start_date.valueOf()==b.start_date.valueOf()?a.id>b.id?1:-1:a.start_date>b.start_date?1:-1});for(var c=[],e=b.length,i=0;i<e;i++){var f=b[i];f._inner=!1;for(var j=this.round_position?y.apply(this,[f.start_date,!1]):f.start_date,g=this.round_position?y.apply(this,[f.end_date,!0]):f.end_date;c.length;){var l=c[c.length-1];if(l.end_date.valueOf()<=j.valueOf())c.splice(c.length-
1,1);else break}for(var o=!1,n=0;n<c.length;n++){var m=c[n];if(m.end_date.valueOf()<=j.valueOf()){o=!0;f._sorder=m._sorder;c.splice(n,1);f._inner=!0;break}}if(c.length)c[c.length-1]._inner=!0;if(!o)if(c.length)if(c.length<=c[c.length-1]._sorder){if(c[c.length-1]._sorder)for(var h=0;h<c.length;h++){for(var p=!1,q=0;q<c.length;q++)if(c[q]._sorder==h){p=!0;break}if(!p){f._sorder=h;break}}else f._sorder=0;f._inner=!0}else{for(var p=c[0]._sorder,k=1;k<c.length;k++)if(c[k]._sorder>p)p=c[k]._sorder;f._sorder=
p+1;f._inner=!1}else f._sorder=0;c.push(f);c.length>(c.max_count||0)?(c.max_count=c.length,f._count=c.length):f._count=f._count?f._count:1}for(var r=0;r<b.length;r++)b[r]._count=c.max_count;for(var s=0;s<e;s++)d+=a.render_timeline_event.call(this,b[s],!1)}return d}function J(b){var d="<table style='table-layout:fixed;' cellspacing='0' cellpadding='0'>",c=[];a._load_mode&&a._load();if(this.render=="cell")c=H.call(this);else for(var e=a.get_visible_events(),i=this.order,f=0;f<e.length;f++){var j=e[f],
g=j[this.y_property],l=this.order[g];if(this.show_unassigned&&!g)for(var o in i){if(i.hasOwnProperty(o)){l=i[o];c[l]||(c[l]=[]);var n=a._lame_copy({},j);n[this.y_property]=o;c[l].push(n)}}else c[l]||(c[l]=[]),c[l].push(j)}for(var m=0,h=0;h<a._cols.length;h++)m+=a._cols[h];var p=new Date;this._step=p=(a.date.add(p,this.x_step*this.x_size,this.x_unit)-p)/m;this._summ=m;var q=a._colsS.heights=[];this._events_height={};this._section_height={};for(h=0;h<this.y_unit.length;h++){var k=this._logic(this.render,
this.y_unit[h],this);a._merge(k,{height:this.dy});if(this.section_autoheight){if(this.y_unit.length*k.height<b.offsetHeight)k.height=Math.max(k.height,Math.floor((b.offsetHeight-1)/this.y_unit.length));this._section_height[this.y_unit[h].key]=k.height}a._merge(k,{tr_className:"",style_height:"height:"+k.height+"px;",style_width:"width:"+(this.dx-1)+"px;",td_className:"dhx_matrix_scell"+(a.templates[this.name+"_scaley_class"](this.y_unit[h].key,this.y_unit[h].label,this.y_unit[h])?" "+a.templates[this.name+
"_scaley_class"](this.y_unit[h].key,this.y_unit[h].label,this.y_unit[h]):""),td_content:a.templates[this.name+"_scale_label"](this.y_unit[h].key,this.y_unit[h].label,this.y_unit[h]),summ_width:"width:"+m+"px;",table_className:""});var r=I.call(this,c[h]);if(this.fit_events){var s=this._events_height[this.y_unit[h].key]||0;k.height=s>k.height?s:k.height;k.style_height="height:"+k.height+"px;";this._section_height[this.y_unit[h].key]=k.height}d+="<tr class='"+k.tr_className+"' style='"+k.style_height+
"'><td class='"+k.td_className+"' style='"+k.style_width+" height:"+(k.height-1)+"px;'>"+k.td_content+"</td>";if(this.render=="cell")for(f=0;f<a._cols.length;f++)d+="<td class='dhx_matrix_cell "+a.templates[this.name+"_cell_class"](c[h][f],this._trace_x[f],this.y_unit[h])+"' style='width:"+(a._cols[f]-1)+"px'><div style='width:"+(a._cols[f]-1)+"px'>"+a.templates[this.name+"_cell_value"](c[h][f])+"</div></td>";else{d+="<td><div style='"+k.summ_width+" "+k.style_height+" position:relative;' class='dhx_matrix_line'>";
d+=r;d+="<table class='"+k.table_className+"' cellpadding='0' cellspacing='0' style='"+k.summ_width+" "+k.style_height+"' >";for(f=0;f<a._cols.length;f++)d+="<td class='dhx_matrix_cell "+a.templates[this.name+"_cell_class"](c[h],this._trace_x[f],this.y_unit[h])+"' style='width:"+(a._cols[f]-1)+"px'><div style='width:"+(a._cols[f]-1)+"px'></div></td>";d+="</table>";d+="</div></td>"}d+="</tr>"}d+="</table>";this._matrix=c;b.innerHTML=d;a._rendered=[];for(var t=a._obj.getElementsByTagName("DIV"),h=0;h<
t.length;h++)t[h].getAttribute("event_id")&&a._rendered.push(t[h]);this._scales={};for(h=0;h<b.firstChild.rows.length;h++){q.push(b.firstChild.rows[h].offsetHeight);var u=this.y_unit[h].key,z=this._scales[u]=a._isRender("cell")?b.firstChild.rows[h]:b.firstChild.rows[h].childNodes[1].getElementsByTagName("div")[0];a.callEvent("onScaleAdd",[z,u])}}function K(b){var d=a.xy.scale_height,c=this._header_resized||a.xy.scale_height;a._cols=[];a._colsS={height:0};this._trace_x=[];var e=a._x-this.dx-18,i=[this.dx],
f=a._els.dhx_cal_header[0];f.style.width=i[0]+e+"px";for(var j=a._min_date_timeline=a._min_date,g=0;g<this.x_size;g++)this._trace_x[g]=new Date(j),j=a.date.add(j,this.x_step,this.x_unit),a._cols[g]=Math.floor(e/(this.x_size-g)),e-=a._cols[g],i[g+1]=i[g]+a._cols[g];b.innerHTML="<div></div>";if(this.second_scale){for(var l=this.second_scale.x_unit,o=[this._trace_x[0]],n=[],m=[this.dx,this.dx],h=0,p=0;p<this._trace_x.length;p++){var q=this._trace_x[p],k=E(l,q,o[h]);k&&(++h,o[h]=q,m[h+1]=m[h]);var r=
h+1;n[h]=a._cols[p]+(n[h]||0);m[r]+=a._cols[p]}b.innerHTML="<div></div><div></div>";var s=b.firstChild;s.style.height=c+"px";var t=b.lastChild;t.style.position="relative";for(var u=0;u<o.length;u++){var z=o[u],A=a.templates[this.name+"_second_scalex_class"](z),x=document.createElement("DIV");x.className="dhx_scale_bar dhx_second_scale_bar"+(A?" "+A:"");a.set_xy(x,n[u]-1,c-3,m[u],0);x.innerHTML=a.templates[this.name+"_second_scale_date"](z);s.appendChild(x)}}a.xy.scale_height=c;for(var b=b.lastChild,
v=0;v<this._trace_x.length;v++){j=this._trace_x[v];a._render_x_header(v,i[v],j,b);var B=a.templates[this.name+"_scalex_class"](j);B&&(b.lastChild.className+=" "+B)}a.xy.scale_height=d;var w=this._trace_x;b.onclick=function(b){var c=F(b);c&&a.callEvent("onXScaleClick",[c.x,w[c.x],b||event])};b.ondblclick=function(b){var c=F(b);c&&a.callEvent("onXScaleDblClick",[c.x,w[c.x],b||event])}}function E(b,d,c){switch(b){case "hour":return d.getHours()!=c.getHours()||E("day",d,c);case "day":return!(d.getDate()==
c.getDate()&&d.getMonth()==c.getMonth()&&d.getFullYear()==c.getFullYear());case "week":return!(a.date.getISOWeek(d)==a.date.getISOWeek(c)&&d.getFullYear()==c.getFullYear());case "month":return!(d.getMonth()==c.getMonth()&&d.getFullYear()==c.getFullYear());case "year":return d.getFullYear()!=c.getFullYear();default:return!1}}function L(b){if(b){a.set_sizes();G();var d=a._min_date;K.call(this,a._els.dhx_cal_header[0]);J.call(this,a._els.dhx_cal_data[0]);a._min_date=d;a._els.dhx_cal_date[0].innerHTML=
a.templates[this.name+"_date"](a._min_date,a._max_date);a.markNow&&a.markNow()}C()}function C(){if(a._tooltip)a._tooltip.style.display="none",a._tooltip.date=""}function M(b,d,c){if(b.render=="cell"){var e=d.x+"_"+d.y,i=b._matrix[d.y][d.x];if(!i)return C();i.sort(function(a,b){return a.start_date>b.start_date?1:-1});if(a._tooltip){if(a._tooltip.date==e)return;a._tooltip.innerHTML=""}else{var f=a._tooltip=document.createElement("DIV");f.className="dhx_year_tooltip";document.body.appendChild(f);f.onclick=
a._click.dhx_cal_data}for(var j="",g=0;g<i.length;g++){var l=i[g].color?"background-color:"+i[g].color+";":"",o=i[g].textColor?"color:"+i[g].textColor+";":"";j+="<div class='dhx_tooltip_line' event_id='"+i[g].id+"' style='"+l+""+o+"'>";j+="<div class='dhx_tooltip_date'>"+(i[g]._timed?a.templates.event_date(i[g].start_date):"")+"</div>";j+="<div class='dhx_event_icon icon_details'>&nbsp;</div>";j+=a.templates[b.name+"_tooltip"](i[g].start_date,i[g].end_date,i[g])+"</div>"}a._tooltip.style.display=
"";a._tooltip.style.top="0px";a._tooltip.style.left=document.body.offsetWidth-c.left-a._tooltip.offsetWidth<0?c.left-a._tooltip.offsetWidth+"px":c.left+d.src.offsetWidth+"px";a._tooltip.date=e;a._tooltip.innerHTML=j;a._tooltip.style.top=document.body.offsetHeight-c.top-a._tooltip.offsetHeight<0?c.top-a._tooltip.offsetHeight+d.src.offsetHeight+"px":c.top+"px"}}function G(){dhtmlxEvent(a._els.dhx_cal_data[0],"mouseover",function(b){var d=a.matrix[a._mode];if(d&&d.render=="cell"){if(d){var c=a._locate_cell_timeline(b),
b=b||event,e=b.target||b.srcElement;if(c)return M(d,c,getOffset(c.src))}C()}});G=function(){}}function N(a){for(var d=a.parentNode.childNodes,c=0;c<d.length;c++)if(d[c]==a)return c;return-1}function F(a){for(var a=a||event,d=a.target?a.target:a.srcElement;d&&d.tagName!="DIV";)d=d.parentNode;if(d&&d.tagName=="DIV"){var c=d.className.split(" ")[0];if(c=="dhx_scale_bar")return{x:N(d),y:-1,src:d,scale:!0}}}a.matrix={};a._merge=function(a,d){for(var c in d)typeof a[c]=="undefined"&&(a[c]=d[c])};a.createTimelineView=
function(b){a._merge(b,{section_autoheight:!0,name:"matrix",x:"time",y:"time",x_step:1,x_unit:"hour",y_unit:"day",y_step:1,x_start:0,x_size:24,y_start:0,y_size:7,render:"cell",dx:200,dy:50,event_dy:a.xy.bar_height-5,event_min_dy:a.xy.bar_height-5,resize_events:!0,fit_events:!0,show_unassigned:!1,second_scale:!1,round_position:!1,_logic:function(b,c,d){var e={};a.checkEvent("onBeforeViewRender")&&(e=a.callEvent("onBeforeViewRender",[b,c,d]));return e}});b._original_x_start=b.x_start;a.checkEvent("onTimelineCreated")&&
a.callEvent("onTimelineCreated",[b]);var d=a.render_data;a.render_data=function(c,f){if(this._mode==b.name)if(f&&!b.show_unassigned&&b.render!="cell")for(var e=0;e<c.length;e++)this.clear_event(c[e]),this.render_timeline_event.call(this.matrix[this._mode],c[e],!0);else a.renderMatrix.call(b,!0,!0);else return d.apply(this,arguments)};a.matrix[b.name]=b;a.templates[b.name+"_cell_value"]=function(a){return a?a.length:""};a.templates[b.name+"_cell_class"]=function(){return""};a.templates[b.name+"_scalex_class"]=
function(){return""};a.templates[b.name+"_second_scalex_class"]=function(){return""};a.templates[b.name+"_scaley_class"]=function(){return""};a.templates[b.name+"_scale_label"]=function(a,b){return b};a.templates[b.name+"_tooltip"]=function(a,b,c){return c.text};a.templates[b.name+"_date"]=function(b,c){return b.getDay()==c.getDay()&&c-b<864E5||+b==+a.date.date_part(new Date(c))||+a.date.add(b,1,"day")==+c&&c.getHours()==0&&c.getMinutes()==0?a.templates.day_date(b):b.getDay()!=c.getDay()&&c-b<864E5?
a.templates.day_date(b)+" &ndash; "+a.templates.day_date(c):a.templates.week_date(b,c)};a.templates[b.name+"_scale_date"]=a.date.date_to_str(b.x_date||a.config.hour_date);a.templates[b.name+"_second_scale_date"]=a.date.date_to_str(b.second_scale&&b.second_scale.x_date?b.second_scale.x_date:a.config.hour_date);a.date["add_"+b.name]=function(c,d){var e=a.date.add(c,(b.x_length||b.x_size)*d*b.x_step,b.x_unit);if((b.x_unit=="minute"||b.x_unit=="hour")&&!b.x_length)if(+a.date.date_part(new Date(c))==+a.date.date_part(new Date(e)))b.x_start+=
d*b.x_size;else{var g=b.x_unit=="hour"?b.x_step*60:b.x_step,l=1440/(b.x_size*g)-1;d>0?b.x_start-=l*b.x_size:b.x_start=l*b.x_size+b.x_start}return e};a.attachEvent("onBeforeTodayDisplayed",function(){b.x_start=b._original_x_start;return!0});a.date[b.name+"_start"]=function(c){var d=a.date[b.x_unit+"_start"]||a.date.day_start,e=d.call(a.date,c);return e=a.date.add(e,b.x_step*b.x_start,b.x_unit)};a.attachEvent("onSchedulerResize",function(){return this._mode==b.name?(a.renderMatrix.call(b,!0,!0),!1):
!0});a.attachEvent("onOptionsLoad",function(){b.order={};a.callEvent("onOptionsLoadStart",[]);for(var c=0;c<b.y_unit.length;c++)b.order[b.y_unit[c].key]=c;a.callEvent("onOptionsLoadFinal",[]);a._date&&b.name==a._mode&&a.setCurrentView(a._date,a._mode)});a.callEvent("onOptionsLoad",[b]);a[b.name+"_view"]=function(){a.renderMatrix.apply(b,arguments)};var c=new Date,e=a.date.add(c,b.x_step,b.x_unit).valueOf()-c.valueOf();a["mouse_"+b.name]=function(c){var d=this._drag_event;if(this._drag_id)d=this.getEvent(this._drag_id),
this._drag_event._dhx_changed=!0;c.x-=b.dx;for(var e=0,g=0,l=0;g<=this._cols.length-1;g++){var o=this._cols[g];e+=o;if(e>c.x){var n=(c.x-(e-o))/o,n=n<0?0:n;break}}for(e=0;l<this._colsS.heights.length;l++)if(e+=this._colsS.heights[l],e>c.y)break;c.fields={};b.y_unit[l]||(l=b.y_unit.length-1);if(l>=0&&b.y_unit[l]&&(c.section=c.fields[b.y_property]=b.y_unit[l].key,d))d[b.y_property]=c.section;c.x=0;c.force_redraw=!0;c.custom=!0;var m;if(g>=b._trace_x.length)m=a.date.add(b._trace_x[b._trace_x.length-
1],b.x_step,b.x_unit);else{var h=b._trace_x[g+1]?b._trace_x[g+1]:a.date.add(b._trace_x[b._trace_x.length-1],b.x_step,b.x_unit),p=Math.ceil(n*(h-b._trace_x[g]));m=new Date(+b._trace_x[g]+p)}if(this._drag_mode=="move"&&this._drag_id&&this._drag_event){var d=this.getEvent(this._drag_id),q=this._drag_event;if(!q._move_delta)q._move_delta=(d.start_date-m)/6E4;m=a.date.add(m,q._move_delta,"minute")}if(this._drag_mode=="resize"&&d)c.resize_from_start=!!(Math.abs(d.start_date-m)<Math.abs(d.end_date-m));if(b.round_position)switch(this._drag_mode){case "move":m=
y.call(b,m,!1);if(b.x_unit=="day")c.custom=!1;break;case "resize":if(this._drag_event){if(this._drag_event._resize_from_start==null)this._drag_event._resize_from_start=c.resize_from_start;c.resize_from_start=this._drag_event._resize_from_start;m=y.call(b,m,!this._drag_event._resize_from_start)}}c.y=Math.round((m-this._min_date)/(6E4*this.config.time_step));c.shift=this.config.time_step;return c}};a.render_timeline_event=function(b,d){var c=b[this.y_property];if(!c)return"";var e=b._sorder,i=w(b,!1,
this),f=w(b,!0,this),j=this.event_dy;this.event_dy=="full"&&(j=this.section_autoheight?this._section_height[c]-6:this.dy-3);this.resize_events&&(j=Math.max(Math.floor(j/b._count),this.event_min_dy));var g=j-2;!b._inner&&this.event_dy=="full"&&(g=(g+2)*(b._count-e)-2);var l=2+e*j+(e?e*2:0);a.config.cascade_event_display&&(l=2+e*a.config.cascade_event_margin+(e?e*2:0));var o=j+l+2;if(!this._events_height[c]||this._events_height[c]<o)this._events_height[c]=o;var n=a.templates.event_class(b.start_date,
b.end_date,b),n="dhx_cal_event_line "+(n||""),m=b.color?"background:"+b.color+";":"",h=b.textColor?"color:"+b.textColor+";":"",p=a.templates.event_bar_text(b.start_date,b.end_date,b),q='<div event_id="'+b.id+'" class="'+n+'" style="'+m+""+h+"position:absolute; top:"+l+"px; height: "+g+"px; left:"+i+"px; width:"+Math.max(0,f-i)+"px;"+(b._text_style||"")+'">';if(a.config.drag_resize&&!a.config.readonly){var k="dhx_event_resize";q+="<div class='"+k+" "+k+"_start' style='height: "+g+"px;'></div><div class='"+
k+" "+k+"_end' style='height: "+g+"px;'></div>"}q+=p+"</div>";if(d){var r=document.createElement("DIV");r.innerHTML=q;var s=this.order[c],t=a._els.dhx_cal_data[0].firstChild.rows[s].cells[1].firstChild;a._rendered.push(r.firstChild);t.appendChild(r.firstChild)}else return q};a.renderMatrix=function(b,d){if(!d)a._els.dhx_cal_data[0].scrollTop=0;a._min_date=a.date[this.name+"_start"](a._date);a._max_date=a.date.add(a._min_date,this.x_size*this.x_step,this.x_unit);a._table_view=!0;if(this.second_scale){if(b&&
!this._header_resized)this._header_resized=a.xy.scale_height,a.xy.scale_height*=2,a._els.dhx_cal_header[0].className+=" dhx_second_cal_header";if(!b&&this._header_resized){a.xy.scale_height/=2;this._header_resized=!1;var c=a._els.dhx_cal_header[0];c.className=c.className.replace(/ dhx_second_cal_header/gi,"")}}L.call(this,b)};a._locate_cell_timeline=function(b){for(var b=b||event,d=b.target?b.target:b.srcElement,c={},e=a.matrix[a._mode],i=a.getActionData(b),f=0;f<e._trace_x.length-1;f++)if(+i.date<
e._trace_x[f+1])break;c.x=f;c.y=e.order[i.section];var j=a._isRender("cell")?1:0;c.src=e._scales[i.section]?e._scales[i.section].getElementsByTagName("td")[f+j]:null;for(var g=!1;c.x==0&&d.className!="dhx_cal_data"&&d.parentNode;)if(d.className.split(" ")[0]=="dhx_matrix_scell"){g=!0;break}else d=d.parentNode;if(g)c.x=-1,c.src=d,c.scale=!0;return c};var O=a._click.dhx_cal_data;a._click.dhx_marked_timespan=a._click.dhx_cal_data=function(b){var d=O.apply(this,arguments),c=a.matrix[a._mode];if(c){var e=
a._locate_cell_timeline(b);e&&(e.scale?a.callEvent("onYScaleClick",[e.y,c.y_unit[e.y],b||event]):a.callEvent("onCellClick",[e.x,e.y,c._trace_x[e.x],(c._matrix[e.y]||{})[e.x]||[],b||event]))}return d};a.dblclick_dhx_marked_timespan=a.dblclick_dhx_matrix_cell=function(b){var d=a.matrix[a._mode];if(d){var c=a._locate_cell_timeline(b);c&&(c.scale?a.callEvent("onYScaleDblClick",[c.y,d.y_unit[c.y],b||event]):a.callEvent("onCellDblClick",[c.x,c.y,d._trace_x[c.x],(d._matrix[c.y]||{})[c.x]||[],b||event]))}};
a.dblclick_dhx_matrix_scell=function(b){return a.dblclick_dhx_matrix_cell(b)};a._isRender=function(b){return a.matrix[a._mode]&&a.matrix[a._mode].render==b};a.attachEvent("onCellDblClick",function(b,d,c,e,i){if(!(this.config.readonly||i.type=="dblclick"&&!this.config.dblclick_create)){var f=a.matrix[a._mode],j={};j.start_date=f._trace_x[b];j.end_date=f._trace_x[b+1]?f._trace_x[b+1]:a.date.add(f._trace_x[b],f.x_step,f.x_unit);j[f.y_property]=f.y_unit[d].key;a.addEventNow(j,null,i)}});a.attachEvent("onBeforeDrag",
function(){return!a._isRender("cell")});a.attachEvent("onEventChanged",function(a,d){d._timed=this.is_one_day_event(d)});var P=a._render_marked_timespan;a._render_marked_timespan=function(b,d,c){if(!a.config.display_marked_timespans)return[];if(a.matrix&&a.matrix[a._mode]){if(!a._isRender("cell")){var e=a.matrix[a._mode],i=[],f=[],j=[];if(c)j=[d],f=[c];else{var g=e.order,l;for(l in g)g.hasOwnProperty(l)&&(f.push(l),j.push(e._scales[l]))}var o=a._min_date,n=a._max_date,m=[];if(b.days>6){var h=new Date(b.days);
a.date.date_part(new Date(o))<=+h&&+n>=+h&&m.push(h)}else m.push.apply(m,a._get_dates_by_index(b.days));for(var p=b.zones,q=a._get_css_classes_by_config(b),k=0;k<f.length;k++)for(var d=j[k],c=f[k],r=0;r<m.length;r++)for(var s=m[r],t=0;t<p.length;t+=2){var u=p[t],z=p[t+1],A=new Date(+s+u*6E4),x=new Date(+s+z*6E4);if(a._min_date<x&&a._max_date>A){var v=a._get_block_by_config(b);v.className=q;var B=w({start_date:A},!1,e)-1,y=w({start_date:x},!1,e)-1,C=Math.max(1,y-B-1),D=e._section_height[c]-1;v.style.cssText=
"height: "+D+"px; left: "+B+"px; width: "+C+"px; top: 0;";d.insertBefore(v,d.firstChild);i.push(v)}}return i}}else return P.apply(a,[b,d,c])};var Q=a._append_mark_now;a._append_mark_now=function(b,d){if(a.matrix&&a.matrix[a._mode]){var c=a._currentDate(),e=a._get_zone_minutes(c),i={days:+a.date.date_part(c),zones:[e,e+1],css:"dhx_matrix_now_time",type:"dhx_now_time"};return a._render_marked_timespan(i)}else return Q.apply(a,[b,d])};a.attachEvent("onScaleAdd",function(b,d){var c=a._marked_timespans;
if(c&&a.matrix&&a.matrix[a._mode])for(var e=a._mode,i=a._min_date,f=a._max_date,j=c.global,g=a.date.date_part(new Date(i));g<f;g=a.date.add(g,1,"day")){var l=+g,o=g.getDay(),n=[],m=j[l]||j[o];n.push.apply(n,a._get_configs_to_render(m));if(c[e]&&c[e][d]){var h=a._get_types_to_render(c[e][d][o],c[e][d][l]);n.push.apply(n,a._get_configs_to_render(h))}for(var p=0;p<n.length;p++){var q=n[p],k=q.days;k<7?(k=l,a._render_marked_timespan(q,b,d),k=o):a._render_marked_timespan(q,b,d)}}})})()});
