/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(b){(function(){b.config.container_autoresize=!0;b.config.month_day_min_height=90;var p=b._pre_render_events;b._pre_render_events=function(d,k){if(!b.config.container_autoresize)return p.apply(this,arguments);var h=this.xy.bar_height,j=this._colsS.heights,a=this._colsS.heights=[0,0,0,0,0,0,0],c=this._els.dhx_cal_data[0],d=this._table_view?this._pre_render_events_table(d,k):this._pre_render_events_line(d,k);if(this._table_view)if(k)this._colsS.heights=j;else{var f=c.firstChild;
if(f.rows){for(var e=0;e<f.rows.length;e++){a[e]++;if(a[e]*h>this._colsS.height-22){for(var g=f.rows[e].cells,l=0;l<g.length;l++)g[l].childNodes[1].style.height=a[e]*h+"px";a[e]=(a[e-1]||0)+g[0].offsetHeight}a[e]=(a[e-1]||0)+f.rows[e].cells[0].offsetHeight}a.unshift(0)}else if(!d.length&&this._els.dhx_multi_day[0].style.visibility=="visible"&&(a[0]=-1),d.length||a[0]==-1){var n=f.parentNode.childNodes,m=(a[0]+1)*h+1+"px";c.style.top=this._els.dhx_cal_navline[0].offsetHeight+this._els.dhx_cal_header[0].offsetHeight+
parseInt(m,10)+"px";c.style.height=this._obj.offsetHeight-parseInt(c.style.top,10)-(this.xy.margin_top||0)+"px";var i=this._els.dhx_multi_day[0];i.style.height=m;i.style.visibility=a[0]==-1?"hidden":"visible";i=this._els.dhx_multi_day[1];i.style.height=m;i.style.visibility=a[0]==-1?"hidden":"visible";i.className=a[0]?"dhx_multi_day_icon":"dhx_multi_day_icon_small";this._dy_shift=(a[0]+1)*h;a[0]=0}}return d};var n=["dhx_cal_navline","dhx_cal_header","dhx_multi_day","dhx_cal_data"],o=function(d){for(var g=
0,h=0;h<n.length;h++){var j=n[h],a=b._els[j]?b._els[j][0]:null,c=0;switch(j){case "dhx_cal_navline":case "dhx_cal_header":c=parseInt(a.style.height,10);break;case "dhx_multi_day":c=a?a.offsetHeight:0;c==1&&(c=0);break;case "dhx_cal_data":var c=Math.max(a.offsetHeight-1,a.scrollHeight),f=b.getState().mode;if(f=="month"){if(b.config.month_day_min_height&&!d)var e=a.getElementsByTagName("tr").length,c=e*b.config.month_day_min_height;if(d)a.style.height=c+"px"}if(b.matrix&&b.matrix[f])d?(c+=2,a.style.height=
c+"px"):c=b.matrix[f].y_unit.length*b.matrix[f].dy+2;if(f=="day"||f=="week")c+=2}g+=c}b._obj.style.height=g+"px";d||b.updateView()},g=function(){var d=b.getState().mode;o();(b.matrix&&b.matrix[d]||d=="month")&&window.setTimeout(function(){o(!0)},1)};b.attachEvent("onViewChange",g);b.attachEvent("onXLE",g);b.attachEvent("onEventChanged",g);b.attachEvent("onAfterSchedulerResize",g)})()});
