/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(a){a.config.limit_start=null;a.config.limit_end=null;a.config.limit_view=!1;a.config.check_limits=!0;a.config.mark_now=!0;a.config.display_marked_timespans=!0;(a._temp_limit_scope=function(){var z=null,t="dhx_time_block",G=function(a,b,c){b instanceof Date&&c instanceof Date?(a.start_date=b,a.end_date=c):(a.days=b,a.zones=c);return a},E=function(a,b,c){var e=typeof a=="object"?a:{days:a};e.type=t;e.css="";if(b){if(c)e.sections=c;e=G(e,a,b)}return e};a.blockTime=function(d,
b,c){var e=E(d,b,c);return a.addMarkedTimespan(e)};a.unblockTime=function(d,b,c){var b=b||"fullday",e=E(d,b,c);return a.deleteMarkedTimespan(e)};a.attachEvent("onBeforeViewChange",function(d,b,c,e){e=e||b;c=c||d;return a.config.limit_view&&(e.valueOf()>a.config.limit_end.valueOf()||this.date.add(e,1,c)<=a.config.limit_start.valueOf())?(setTimeout(function(){a.setCurrentView(a._date,c)},1),!1):!0});var F=function(a,b,c){var e=c[b]&&c[b][t]?c[b][t]:c[a]&&c[a][t]?c[a][t]:[];return e},v=a.checkLimitViolation=
function(d){function b(b,d,c,e){var f=[];if(b&&b[d])for(var g=b[d],h=F(c,e,g),i=0;i<h.length;i++)f=a._add_timespan_zones(f,h[i].zones);return f}if(!d)return!0;if(!a.config.check_limits)return!0;for(var c=a,e=c._mode,f=a._marked_timespans,g=c.config,i=[],i=d.rec_type?a.getRecDates(d):[d],h=!0,j=0;j<i.length;j++){var l=!0,k=i[j];k._timed=a.is_one_day_event(k);if(l=g.limit_start&&g.limit_end?k.start_date.valueOf()>=g.limit_start.valueOf()&&k.end_date.valueOf()<=g.limit_end.valueOf():!0)for(var n=new Date(k.start_date.valueOf()),
p=a.date.add(n,1,"day");n<k.end_date;n=a.date.date_part(p),p=c.date.add(n,1,"day")){var q=+a.date.date_part(new Date(n)),m=n.getDay(),o=[],r={_props:"map_to",matrix:"y_property"},u;for(u in r){var s=r[u];if(c[u])for(var t in c[u]){var v=c[u][t],z=v[s];k[z]&&(o=a._add_timespan_zones(o,b(f[t],k[z],m,q)))}}for(var D=f.global,C=F(m,q,D),x=0;x<C.length;x++)o=a._add_timespan_zones(o,C[x].zones);if(o)for(x=0;x<o.length;x+=2){var A=a._get_zone_minutes(n),y=k.end_date>p||k.end_date.getDate()!=n.getDate()?
1440:a._get_zone_minutes(k.end_date),B=o[x],w=o[x+1];if(B<y&&w>A){if(A<=w&&A>=B){if(w==1440||y<w){l=!1;break}if(k._timed&&c._drag_id&&c._drag_mode=="new-size")k.start_date.setHours(0),k.start_date.setMinutes(w);else{l=!1;break}}if(y>=B&&y<w||A<B&&y>w)if(k._timed&&c._drag_id&&c._drag_mode=="new-size")k.end_date.setHours(0),k.end_date.setMinutes(B);else{l=!1;break}}}}if(!l)c._drag_id=null,c._drag_mode=null,l=c.checkEvent("onLimitViolation")?c.callEvent("onLimitViolation",[k.id,k]):l;h=h&&l}return h};
a.attachEvent("onMouseDown",function(a){return!(a=t)});a.attachEvent("onBeforeDrag",function(d){return!d?!0:v(a.getEvent(d))});a.attachEvent("onClick",function(d){return v(a.getEvent(d))});a.attachEvent("onBeforeLightbox",function(d){var b=a.getEvent(d);z=[b.start_date,b.end_date];return v(b)});a.attachEvent("onEventSave",function(d,b){if(!b.start_date||!b.end_date){var c=a.getEvent(d);b.start_date=b.start_date||new Date(c.start_date);b.end_date=b.end_date||new Date(c.end_date)}if(b.rec_type){var e=
a._lame_clone(b);a._roll_back_dates(e);return v(e)}return v(b)});a.attachEvent("onEventAdded",function(d){if(!d)return!0;var b=a.getEvent(d);if(!v(b)&&a.config.limit_start&&a.config.limit_end){if(b.start_date<a.config.limit_start)b.start_date=new Date(a.config.limit_start);if(b.start_date.valueOf()>=a.config.limit_end.valueOf())b.start_date=this.date.add(a.config.limit_end,-1,"day");if(b.end_date<a.config.limit_start)b.end_date=new Date(a.config.limit_start);if(b.end_date.valueOf()>=a.config.limit_end.valueOf())b.end_date=
this.date.add(a.config.limit_end,-1,"day");if(b.start_date.valueOf()>=b.end_date.valueOf())b.end_date=this.date.add(b.start_date,this.config.event_duration||this.config.time_step,"minute");b._timed=this.is_one_day_event(b)}return!0});a.attachEvent("onEventChanged",function(d){if(!d)return!0;var b=a.getEvent(d);if(!v(b)){if(!z)return!1;b.start_date=z[0];b.end_date=z[1];b._timed=this.is_one_day_event(b)}return!0});a.attachEvent("onBeforeEventChanged",function(a){return v(a)});a.attachEvent("onBeforeEventCreated",
function(d){var b=a.getActionData(d).date,c={_timed:!0,start_date:b,end_date:a.date.add(b,a.config.time_step,"minute")};return v(c)});a.attachEvent("onViewChange",function(){a.markNow()});a.attachEvent("onSchedulerResize",function(){window.setTimeout(function(){a.markNow()},1);return!0});a.attachEvent("onTemplatesReady",function(){a._mark_now_timer=window.setInterval(function(){a.markNow()},6E4)});a.markNow=function(d){var b="dhx_now_time";this._els[b]||(this._els[b]=[]);var c=a._currentDate(),e=
this.config;a._remove_mark_now();if(!d&&e.mark_now&&c<this._max_date&&c>this._min_date&&c.getHours()>=e.first_hour&&c.getHours()<e.last_hour){var f=this.locate_holder_day(c);this._els[b]=a._append_mark_now(f,c)}};a._append_mark_now=function(d,b){var c="dhx_now_time",e=a._get_zone_minutes(b),f={zones:[e,e+1],css:c,type:c};if(this._table_view){if(this._mode=="month")return f.days=+a.date.date_part(b),a._render_marked_timespan(f,null,null)}else if(this._props&&this._props[this._mode]){for(var g=this._els.dhx_cal_data[0].childNodes,
i=[],h=0;h<g.length-1;h++){var j=d+h;f.days=j;var l=a._render_marked_timespan(f,null,j)[0];i.push(l)}return i}else return f.days=d,a._render_marked_timespan(f,null,d)};a._remove_mark_now=function(){for(var a="dhx_now_time",b=this._els[a],c=0;c<b.length;c++){var e=b[c],f=e.parentNode;f&&f.removeChild(e)}this._els[a]=[]};a._marked_timespans={global:{}};a._get_zone_minutes=function(a){return a.getHours()*60+a.getMinutes()};a._prepare_timespan_options=function(d){var b=[],c=[];if(d.days=="fullweek")d.days=
[0,1,2,3,4,5,6];if(d.days instanceof Array){for(var e=d.days.slice(),f=0;f<e.length;f++){var g=a._lame_clone(d);g.days=e[f];b.push.apply(b,a._prepare_timespan_options(g))}return b}if(!d||!(d.start_date&&d.end_date&&d.end_date>d.start_date||d.days!==void 0&&d.zones))return b;var i=0,h=1440;if(d.zones=="fullday")d.zones=[i,h];if(d.zones&&d.invert_zones)d.zones=a.invertZones(d.zones);d.id=a.uid();d.css=d.css||"";d.type=d.type||"default";var j=d.sections;if(j)for(var l in j){if(j.hasOwnProperty(l)){var k=
j[l];k instanceof Array||(k=[k]);for(f=0;f<k.length;f++){var n=a._lame_copy({},d);n.sections={};n.sections[l]=k[f];c.push(n)}}}else c.push(d);for(var p=0;p<c.length;p++){var q=c[p],m=q.start_date,o=q.end_date;if(m&&o)for(var r=a.date.date_part(new Date(m)),u=a.date.add(r,1,"day");r<o;){n=a._lame_copy({},q);delete n.start_date;delete n.end_date;n.days=r.valueOf();var s=m>r?a._get_zone_minutes(m):i,t=o>u||o.getDate()!=r.getDate()?h:a._get_zone_minutes(o);n.zones=[s,t];b.push(n);r=u;u=a.date.add(u,1,
"day")}else{if(q.days instanceof Date)q.days=a.date.date_part(q.days).valueOf();q.zones=d.zones.slice();b.push(q)}}return b};a._get_dates_by_index=function(d,b,c){for(var e=[],b=a.date.date_part(new Date(b||a._min_date)),c=new Date(c||a._max_date),f=b.getDay(),g=d-f>=0?d-f:7-b.getDay()+d,i=a.date.add(b,g,"day");i<c;i=a.date.add(i,1,"week"))e.push(i);return e};a._get_css_classes_by_config=function(a){var b=[];a.type==t&&(b.push(t),a.css&&b.push(t+"_reset"));b.push("dhx_marked_timespan",a.css);return b.join(" ")};
a._get_block_by_config=function(a){var b=document.createElement("DIV");if(a.html)typeof a.html=="string"?b.innerHTML=a.html:b.appendChild(a.html);return b};a._render_marked_timespan=function(d,b,c){var e=[],f=a.config,g=this._min_date,i=this._max_date,h=!1;if(!f.display_marked_timespans)return e;if(!c&&c!==0){if(d.days<7)c=d.days;else{var j=new Date(d.days),h=+j;if(!(+i>=+j&&+g<=+j))return e;c=j.getDay()}var l=g.getDay();l>c?c=7-(l-c):c-=l}var k=d.zones,n=a._get_css_classes_by_config(d);if(a._table_view&&
a._mode=="month"){var p=[],q=[];if(b)p.push(b),q.push(c);else for(var q=h?[h]:a._get_dates_by_index(c),m=0;m<q.length;m++)p.push(this._scales[q[m]]);for(m=0;m<p.length;m++)for(var b=p[m],c=q[m],o=0;o<k.length;o+=2){var r=k[m],u=k[m+1];if(u<=r)return[];var s=a._get_block_by_config(d);s.className=n;var t=b.offsetHeight-1,v=b.offsetWidth-1,z=Math.floor((this._correct_shift(c,1)-g.valueOf())/(864E5*this._cols.length)),D=this.locate_holder_day(c,!1)%this._cols.length,C=this._colsS[D],x=this._colsS.heights[z]+
(this._colsS.height?this.xy.month_scale_height+2:2)-1;s.style.top=x+"px";s.style.lineHeight=s.style.height=t+"px";s.style.left=C+Math.round(r/1440*v)+"px";s.style.width=Math.round((u-r)/1440*v)+"px";b.appendChild(s);e.push(s)}}else{var A=c;if(this._props&&this._props[this._mode]&&d.sections&&d.sections[this._mode]){var y=this._props[this._mode],A=y.order[d.sections[this._mode]];y.size&&A>y.position+y.size&&(A=0)}b=b?b:a.locate_holder(A);for(m=0;m<k.length;m+=2){r=Math.max(k[m],f.first_hour*60);u=
Math.min(k[m+1],f.last_hour*60);if(u<=r)if(m+2<k.length)continue;else return[];s=a._get_block_by_config(d);s.className=n;var B=this.config.hour_size_px*24+1,w=36E5;s.style.top=Math.round((r*6E4-this.config.first_hour*w)*this.config.hour_size_px/w)%B+"px";s.style.lineHeight=s.style.height=Math.max(Math.round((u-r)*6E4*this.config.hour_size_px/w)%B,1)+"px";b.appendChild(s);e.push(s)}}return e};a.markTimespan=function(d){var b=a._prepare_timespan_options(d);if(b.length){for(var c=[],e=0;e<b.length;e++){var f=
b[e],g=a._render_marked_timespan(f,null,null);g.length&&c.push.apply(c,g)}return c}};a.unmarkTimespan=function(a){if(a)for(var b=0;b<a.length;b++){var c=a[b];c.parentNode&&c.parentNode.removeChild(c)}};a._marked_timespans_ids={};a.addMarkedTimespan=function(d){var b=a._prepare_timespan_options(d),c="global";if(b.length){var e=b[0].id,f=a._marked_timespans,g=a._marked_timespans_ids;g[e]||(g[e]=[]);for(var i=0;i<b.length;i++){var h=b[i],j=h.days,l=h.zones,k=h.css,n=h.sections,p=h.type;h.id=e;if(n)for(var q in n){if(n.hasOwnProperty(q)){f[q]||
(f[q]={});var m=n[q],o=f[q];o[m]||(o[m]={});o[m][j]||(o[m][j]={});if(!o[m][j][p]){o[m][j][p]=[];if(!a._marked_timespans_types)a._marked_timespans_types={};a._marked_timespans_types[p]||(a._marked_timespans_types[p]=!0)}var r=o[m][j][p];h._array=r;r.push(h);g[e].push(h)}}else f[c][j]||(f[c][j]={}),f[c][j][p]||(f[c][j][p]=[]),r=f[c][j][p],h._array=r,r.push(h),g[e].push(h)}return e}};a._add_timespan_zones=function(a,b){var c=a.slice(),b=b.slice();if(!c.length)return b;for(var e=0;e<c.length;e+=2)for(var f=
c[e],g=c[e+1],i=e+2==c.length,h=0;h<b.length;h+=2){var j=b[h],l=b[h+1];if(l>g&&j<=g||j<f&&l>=f)c[e]=Math.min(f,j),c[e+1]=Math.max(g,l),e-=2;else{if(!i)continue;var k=f>j?0:2;c.splice(e+k,0,j,l)}b.splice(h--,2);break}return c};a._subtract_timespan_zones=function(a,b){for(var c=a.slice(),e=0;e<c.length;e+=2)for(var f=c[e],g=c[e+1],i=0;i<b.length;i+=2){var h=b[i],j=b[i+1];if(j>f&&h<g){var l=!1;f>=h&&g<=j&&c.splice(e,2);f<h&&(c.splice(e,2,f,h),l=!0);g>j&&c.splice(l?e+2:e,l?0:2,j,g);e-=2;break}}return c};
a.invertZones=function(d){return a._subtract_timespan_zones([0,1440],d.slice())};a._delete_marked_timespan_by_id=function(d){var b=a._marked_timespans_ids[d];if(b)for(var c=0;c<b.length;c++)for(var e=b[c],f=e._array,g=0;g<f.length;g++)if(f[g]==e){f.splice(g,1);break}};a._delete_marked_timespan_by_config=function(d){var b=a._marked_timespans,c=d.sections,e=d.days,f=d.type||"default",g=[];if(c)for(var i in c){if(c.hasOwnProperty(i)&&b[i]){var h=c[i];b[i][h]&&b[i][h][e]&&b[i][h][e][f]&&(g=b[i][h][e][f])}}else b.global[e]&&
b.global[e][f]&&(g=b.global[e][f]);for(var j=0;j<g.length;j++){var l=g[j],k=a._subtract_timespan_zones(l.zones,d.zones);if(k.length)l.zones=k;else{g.splice(j,1);j--;for(var n=a._marked_timespans_ids[l.id],p=0;p<n.length;p++)if(n[p]==l){n.splice(p,1);break}}}};a.deleteMarkedTimespan=function(d){if(!arguments.length)a._marked_timespans={global:{}},a._marked_timespans_ids={},a._marked_timespans_types={};if(typeof d!="object")a._delete_marked_timespan_by_id(d);else{if(!d.start_date||!d.end_date){if(!d.days)d.days=
"fullweek";if(!d.zones)d.zones="fullday"}var b=[];if(d.type)b.push(d.type);else for(var c in a._marked_timespans_types)b.push(c);for(var e=a._prepare_timespan_options(d),f=0;f<e.length;f++)for(var g=e[f],i=0;i<b.length;i++){var h=a._lame_clone(g);h.type=b[i];a._delete_marked_timespan_by_config(h)}}};a._get_types_to_render=function(a,b){var c=a?a:{},e;for(e in b||{})b.hasOwnProperty(e)&&(c[e]=b[e]);return c};a._get_configs_to_render=function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push.apply(b,
a[c]);return b};a.attachEvent("onScaleAdd",function(d,b){if(!(a._table_view&&a._mode!="month")){var c=b.getDay(),e=b.valueOf(),f=this._mode,g=a._marked_timespans,i=[];if(this._props&&this._props[f]){var h=this._props[f],j=h.options,l=a._get_unit_index(h,b),k=j[l],b=a.date.date_part(new Date(this._date)),c=b.getDay(),e=b.valueOf();if(g[f]&&g[f][k.key]){var n=g[f][k.key],p=a._get_types_to_render(n[c],n[e]);i.push.apply(i,a._get_configs_to_render(p))}}var q=g.global,m=q[e]||q[c];i.push.apply(i,a._get_configs_to_render(m));
for(var o=0;o<i.length;o++)a._render_marked_timespan(i[o],d,b)}})})()});
